name: weather
version: '3.8'
services:
  # web:
  #   build:
  #     context: ./web
  #     target: development
  #   container_name: web
  #   environment:
  #     CHOKIDAR_USEPOLLING: true
  #   volumes:
  #     - /app/node_modules
  #     - ./web:/app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - server

  server:
    env_file:
      - ./server/.env.development
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile.server
      target: development
    container_name: server
    environment:
      CHOKIDAR_USEPOLLING: true
    restart: always
    volumes:
      - /app/node_modules
      - ./server/:/app/
    ports:
      - 4000:4000
    depends_on:
      - redis
      - postgres

  postgres:
    env_file:
      - ./server/.env.development
    build:
      context: ./server
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  postgres:
