services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: "bank-system"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      restart: always
      ports:
        - 5050:80
      environment:
        - PGADMIN_DEFAULT_PASSWORD=admin
        - PGADMIN_DEFAULT_EMAIL=admin@admin.admin

